# Generated by Django 2.1.1 on 2018-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
    ]
